swagger: '2.0'

info:
  version: "1.0.0"
  title: Geometry API
  description: API for 3D geometric calculations

host: 'localhost:5000'
basePath: '/api/v1'
schemes:
  - http
  - https

consumes:
  - application/json

produces:
  - application/json

